name: golang-json-assert
on:
  push:
    branches: [ "*" ]
env:
  CI: true
jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
          with:
            go-version: '^1.14.4' # The Go version to download (if necessary) and use.
      - name: Test
        run: go test
        working-directory: pkg
